language: node_js
node_js:
  - "node"
  - "8"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
notifications:
 -  email: false

env:
  global:
     - TRAVIS=true 
     - NODE_ENV=test